/*
Credit: Rico Endico a.k.a yb
Subscribe Channel: Rico Endico
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script

(( TEXTDRAW ONLY!! NOT WITH SCRIPT!!))
(( DON'T SELL THIS SCRIPT! RIGHT?))
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][24];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 320.000000, 95.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 30.050001);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 307.000000, 360.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 320.000000, 110.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 26.549993);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 304.000000, 332.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], -1094795521);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 95.000000, 116.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 251.000000, 230.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 265);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], -10.000000, 0.000000, -4.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 1, 1);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 197.000000, 116.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 251.000000, 230.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][3], 265);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][3], -10.000000, 0.000000, 96.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][3], 1, 1);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 288.000000, 116.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 251.000000, 230.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][4], 265);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][4], -10.000000, 0.000000, 180.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][4], 1, 1);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 320.000000, 220.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 11.549981);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 303.000000, 332.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], -1094795521);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 320.000000, 219.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.641666, -0.400004);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 306.000000, 332.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 320.000000, 220.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 0.950001);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 298.500000, 333.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 1097458175);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 320.000000, 110.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 0.950001);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 298.500000, 333.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 1097458175);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 320.000000, 108.000000, "PERSON_INFO");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 320.000000, 219.000000, "PERSON_DATA");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 177.000000, 242.000000, "Name__:");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 177.000000, 254.000000, "Address:");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 176.000000, 268.000000, "Phone_:");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

	PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 185.000000, 283.000000, "Crime_Record:");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][14], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

	PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 251.000000, 242.000000, "Sebastian_Sachdev");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][15], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

	PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 282.000000, 254.000000, "Los_Santos,_201_Verdant_Bluffs_Street");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

	PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 235.000000, 268.000000, "653-567");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][17], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

	PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 227.000000, 283.000000, "Yes");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][18], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 0);

	PlayerTD[playerid][19] = CreatePlayerTextDraw(playerid, 189.000000, 297.000000, "Driving_Licenses:");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][19], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][19], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][19], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][19], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][19], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][19], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][19], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][19], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][19], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][19], 0);

	PlayerTD[playerid][20] = CreatePlayerTextDraw(playerid, 227.000000, 297.000000, "No");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][20], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][20], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][20], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][20], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][20], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][20], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][20], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][20], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][20], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][20], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][20], 0);

	PlayerTD[playerid][21] = CreatePlayerTextDraw(playerid, 320.000000, 354.000000, "Yb's_PC");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][21], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][21], 0.191667, 1.050000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][21], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][21], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][21], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][21], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][21], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][21], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][21], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][21], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][21], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][21], 0);

	PlayerTD[playerid][22] = CreatePlayerTextDraw(playerid, 482.000000, 111.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][22], 0.600000, 0.650001);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][22], 298.500000, 8.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][22], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][22], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][22], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][22], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][22], -1962934017);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][22], 0);

	PlayerTD[playerid][23] = CreatePlayerTextDraw(playerid, 482.000000, 108.000000, "X");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][23], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][23], 0.291666, 1.100000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][23], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][23], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][23], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][23], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][23], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][23], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][23], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][23], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][23], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][23], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][11]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][12]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][13]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][14]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][15]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][16]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][17]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][18]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][19]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][20]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][21]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][22]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][23]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/mdc Sebastian_Sachdev", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][11]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][13]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][14]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][15]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][16]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][17]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][18]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][19]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][20]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][21]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][22]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][23]);
		return 1;
	}
	return 0;
}
